### ISSUE TITLE
Please fix console error on the oneplayer=true URL

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#1205]
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at i.getImageData (https://widget.sndcdn.com/visual-single-sound-a0e5343-647ac00d.js:3:10872)
    at n.<anonymous> (https://widget.sndcdn.com/visual-single-sound-a0e5343-647ac00d.js:1:2574)
    at c (https://widget.sndcdn.com/widget-3b8c6f0-acab8518.js:2:3839)
    at Object.fireWith [as resolveWith] (https://widget.sndcdn.com/widget-3b8c6f0-acab8518.js:2:4656)
    at Object.i.(anonymous function) (https://widget.sndcdn.com/widget-3b8c6f0-acab8518.js:2:5646)
    at Object.<anonymous> (https://widget.sndcdn.com/widget-3b8c6f0-acab8518.js:2:5219)
    at c (https://widget.sndcdn.com/widget-3b8c6f0-acab8518.js:2:3839)
    at Object.fireWith [as resolveWith] (https://widget.sndcdn.com/widget-3b8c6f0-acab8518.js:2:4656)
    at Object.<anonymous> (https://widget.sndcdn.com/widget-3b8c6f0-acab8518.js:2:5345)
    at c (https://widget.sndcdn.com/widget-3b8c6f0-acab8518.js:2:3839)

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves Looks like this was not fixed yet either, please complete

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves still seeing this error, please fix
