### ISSUE TITLE
Upgrading to nodejs v8.0.0 breaks our project, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#329]
Unhandled rejection Error: Error invoking SVGAnalyzer. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: __WEBPACK_IMPORTED_MODULE_1_aurelia_pal__.b.createElement is not a function
Inner Error Stack:
TypeError: __WEBPACK_IMPORTED_MODULE_1_aurelia_pal__.b.createElement is not a function
    at createElement (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:62096:74)
    at new SVGAnalyzer (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:62105:13)
    at Object.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54322:12)
    at InvocationHandler.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54299:166)
    at Container.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54563:23)
    at StrategyResolver.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54013:35)
    at Container.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54490:39)
    at Object.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54352:103)
    at InvocationHandler.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54299:166)
    at Container.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54563:23)
    at StrategyResolver.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54013:35)
    at Container.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54490:39)
    at HtmlBehaviorResource.initialize (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:5930:38)
    at ResourceDescription.initialize (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17518:19)
    at ResourceModule.initialize (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17438:15)
    at http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17821:18
    at tryCatcher (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:12180:23)
    at Promise._settlePromiseFromHandler (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10202:31)
    at Promise._settlePromise (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10259:18)
    at Promise._settlePromise0 (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10304:10)
    at Promise._settlePromises (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10383:18)
    at Promise._fulfill (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10328:18)
    at PromiseArray._resolve (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10593:19)
    at PromiseArray._promiseFulfilled (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10611:14)
    at Promise._settlePromise (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10264:26)
    at Promise._settlePromise0 (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10304:10)
    at Promise._settlePromises (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:10383:18)
    at http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:7102:25
End Inner Error Stack
------------------------------------------------

    at createElement (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:62096:74)
    at new SVGAnalyzer (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:62105:13)
    at Object.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54322:12)
    at InvocationHandler.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54299:166)
    at Container.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54563:23)
    at StrategyResolver.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54013:35)
    at Container.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54490:39)
    at Object.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54352:103)
    at InvocationHandler.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54299:166)
    at Container.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54563:23)
    at StrategyResolver.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54013:35)
    at Container.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54490:39)
    at HtmlBehaviorResource.initialize (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:5930:38)
    at ResourceDescription.initialize (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17518:19)
    at ResourceModule.initialize (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17438:15)
    at http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17821:18
    at new AggregateError (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:55916:11)
    at Container.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54565:13)
    at StrategyResolver.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54013:35)
    at Container.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54490:39)
    at Object.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54352:103)
    at InvocationHandler.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54299:166)
    at Container.invoke (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54563:23)
    at StrategyResolver.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54013:35)
    at Container.get (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:54490:39)
    at HtmlBehaviorResource.initialize (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:5930:38)
    at ResourceDescription.initialize (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17518:19)
    at ResourceModule.initialize (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17438:15)
    at http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17821:18
From previous event:
    at ViewEngine.importViewResources (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:17805:50)
    at http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:65564:23
From previous event:
    at loadResources (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:65555:7)
    at http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:65632:14
    at next (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:65512:30)
    at runTasks (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:65518:10)
    at http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:65798:16
From previous event:
    at http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:65797:21
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:65782:42)
    at Aurelia.start (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:65398:37)
    at HTMLDocument.<anonymous> (http://localhost:9000/app.2ff7e33a6c5cc2cc35d4.bundle.js:72483:23)
    at http://localhost:9000/webcomponents.min.js:14:20073

**Comment by JoshuaVSherman** [comment]
https://github.com/SpoonX/aurelia-form-validation/issues/4

**Comment by JoshuaVSherman** [comment]
@LinuxBozo if you happen to now how to fix this, i'd be very happy. I failed this morning again on trying to fix this, thanks

**Comment by JoshuaVSherman** [comment]
https://github.com/aurelia/validation/issues/445#issuecomment-307084218
